version: '3.6'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - 3000:3000  
    volumes:
      - '.:/app'  
    environment:
      - NODE_ENV=development