# Base image
FROM node:10.1.0

# Set working directory
RUN mkdir /app
WORKDIR /app

# Copy project to app directory inside the image
COPY . /app
COPY package.json /app/package.json

# Install packages
RUN npm install

# Tell Docker about the port we'll run on.
EXPOSE 3000

# Run the server 
CMD ["npm", "start"]