version: '3.6'

services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000  
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    environment:
      - NODE_ENV=development